### ISSUE TITLE
关于ctrl-proxy.py

### ISSUE THREAD

**Issue by tomhup** [Skythinker616/foc-wheel-legged-robot#4]
在main函数中，采用了两个asyncio.run。导致两个函数串行执行，建议使用asyncio.gather 函数并行执行

**Comment by Skythinker616** [comment]
程序设计的就是两个函数轮流执行，因为图传蓝牙需要作为主机连接控制板，又需要作为从机连接手机，经测试二者无法同时进行，程序会以“是否收到UDP数据”为准则在两种状态之间切换
